"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import struct
import json
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding

class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """
        # TODO: parse your secrets data here and run any necessary pre-processing to
        #   improve the throughput of Encoder.encode

        # Load the json of the secrets file
        secrets = json.loads(secrets)
        
        # In this design, the secret "some_secrets" is expected to be a hex string
        # representing a 128-bit AES key.
        self.key = bytes.fromhex(secrets["some_secrets"])

        # Load the example secrets for use in Encoder.encode
        # This will be "EXAMPLE" in the reference design"
        self.some_secrets = secrets["some_secrets"]
    
    def _encrypt(self, data: bytes) -> bytes:
        print(f"encoder key-> {self.key.hex()}")
        # TODO: handle exceptiopns from crypto library
        cipher = Cipher(algorithms.AES(self.key), modes.ECB(), backend=default_backend())
        encryptor = cipher.encryptor()
        encrypted_data = encryptor.update(data) + encryptor.finalize()
        return encrypted_data
    
    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 16b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """
        # TODO: encode the satellite frames so that they meet functional and
        #  security requirements
        
        print(f"Encoding frame: Channel = {channel}, Timestamp = {timestamp}")

        if len(frame) > 64:
            raise ValueError("Frame size must not exceed 64 bytes.")
        frame_size = len(frame)
        print(f"frame length before encryption ---> {len(frame)}")
        
        if channel < 0:
            raise ValueError("ERROR: channel id can't be negative")
        # TODO: add sanity check for max value of both channel and timestamp
        if timestamp < 0:
             raise ValueError("ERROR: timestamp must be greater than or equal to 0")
        
        if frame_size % 16 != 0:
            frame_padding = 16 - (frame_size % 16)
            frame += b'\x00' * frame_padding
        

        # First round of encryption on just the frame, without padding since it's already 64 bytes
        encrypted_frame = self._encrypt(frame)
        print(f"First encryption complete. Length of encrypted frame: {len(encrypted_frame)} bytes")

        # Pack channel and timestamp into header
        header = struct.pack("<IQI", channel, timestamp, frame_size)
        print(f"Packed Header: {header.hex()} (Channel = {channel}, Timestamp = {timestamp})")
        
        # Prepare the full packet with the encrypted frame
        full_packet = header + encrypted_frame
        print(f"FULL PACKET LENGTH WITHOUT PADDING -> {len(full_packet)}")
        # Padding added to make the total packet size divisible by 16
        if len(full_packet) %16 != 0:
            padding_length = 16 - (len(full_packet) %16) 
            full_packet += b'\x00' * padding_length

        print(f"Full packet length before final encryption (including padding): {len(full_packet)} bytes")
        # Second round of encryption on the entire packet, no additional padding needed as it's set to 80 bytes
        encrypted_packet = self._encrypt(full_packet)
        print(f"Final encryption complete. Length of encrypted packet: {len(encrypted_packet)} bytes")
        
        return encrypted_packet
        #return struct.pack("<IQ", channel, timestamp) + frame


def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets_file.read())
    print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))


if __name__ == "__main__":
    main()