"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import struct
import json
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding
from loguru import logger

class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """
        # TODO: parse your secrets data here and run any necessary pre-processing to
        #   improve the throughput of Encoder.encode

        # Load the json of the secrets file
        secrets = json.loads(secrets)
        
        # channel-specific 128-bit AES keys
        self.channel_keys = {int(c): bytes.fromhex(k) for c, k in secrets["channel_keys"].items()}
        
        # main 128-bit AES key
        self.secret_key = bytes.fromhex(secrets["secret_key"])


        logger.info("Successfully loaded channel keys and secret_key.")
        logger.debug(f"Available channel keys: {list(self.channel_keys.keys())}")
        logger.debug(f"Final encryption key (secret_key): {self.secret_key.hex()}")
        
    
    def _encrypt(self, data: bytes, key: bytes) -> bytes:
        """Encrypt data using AES-ECB mode"""
        logger.debug(f"Encrypting data with key: {key.hex()}")
        # TODO: handle exceptiopns from crypto library
        cipher = Cipher(algorithms.AES(key), modes.ECB(), backend=default_backend())
        encryptor = cipher.encryptor()
        encrypted_data = encryptor.update(data) + encryptor.finalize()
        return encrypted_data
    
    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 16b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """
        # TODO: encode the satellite frames so that they meet functional and
        #  security requirements

        if len(frame) > 64:
            raise ValueError("Frame size must not exceed 64 bytes.")
        frame_size = len(frame)
                
        if channel < 0:
            raise ValueError("ERROR: channel id can't be negative")
        # TODO: add sanity check for max value of both channel and timestamp
        if timestamp < 0:
             raise ValueError("ERROR: timestamp must be greater than or equal to 0")
        
        logger.info(f"Encoding frame for Channel = {channel}, Timestamp = {timestamp}")

        # Pad frame to be a multiple of 16 bytes
        if frame_size % 16 != 0:
            frame_padding = 16 - (frame_size % 16)
            frame += b'\x00' * frame_padding
        logger.info(f"Frame padded to: {len(frame)} bytes (Multiple of 16)")

        # Select encryption key
        if channel == 0:
            channel_key = self.secret_key  # Emergency channel uses secret_key
        else:
            if channel not in self.channel_keys:
                raise ValueError(f"No key found for channel {channel}. Available channels: {list(self.channel_keys.keys())}")
            channel_key = self.channel_keys[channel]
        
        logger.info(f"Using encryption key for channel {channel}: {channel_key.hex()}")




        # First encryption layer on padded frame
        encrypted_frame = self._encrypt(frame, self.secret_key)
        logger.success(f"First encryption complete. Encrypted Frame Size: {len(encrypted_frame)} bytes")



        # Pack header (channel_id + timestamp + frame_size)
        header = struct.pack("<IQI", channel, timestamp, frame_size)
        logger.debug(f"Packed Header: {header.hex()} (Channel = {channel}, Timestamp = {timestamp})")
        
        
        
        # Create full packet with encrypted frame
        full_packet = header + encrypted_frame
        logger.debug(f"Full Packet Length Before Final Padding: {len(full_packet)} bytes")



        # Ensure full packet is a multiple of 16 bytes
        if len(full_packet) % 16 != 0:
            padding_length = 16 - (len(full_packet) % 16)
            full_packet += b'\x00' * padding_length
        
        logger.info(f"Final Packet Size After Padding: {len(full_packet)} bytes (Multiple of 16)")
        
        
        # Second encryption layer
        encrypted_packet = self._encrypt(full_packet, self.secret_key)
        logger.success(f"Final encryption complete. Encrypted Packet Size: {len(encrypted_packet)} bytes")
        
        return encrypted_packet
        #return struct.pack("<IQ", channel, timestamp) + frame


def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets_file.read())
    print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))


if __name__ == "__main__":
    main()