/**
 * @file    decoder.c
 * @author  Samuel Meyers
 * @brief   eCTF Decoder Example Design Implementation
 * @date    2025
 *
 * This source file is part of an example system for MITRE's 2025 Embedded System CTF (eCTF).
 * This code is being provided only for educational purposes for the 2025 MITRE eCTF competition,
 * and may not meet MITRE standards for quality. Use this code at your own risk!
 *
 * @copyright Copyright (c) 2025 The MITRE Corporation
 */

/*********************** INCLUDES *************************/
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "mxc_device.h"
#include "status_led.h"
#include "board.h"
#include "mxc_delay.h"
#include "simple_flash.h"
#include "host_messaging.h"
// secrets key file generated by gen_secrets
#include "secrets.h"

#include <stdlib.h>

#include "simple_uart.h"

/* Code between this #ifdef and the subsequent #endif will
*  be ignored by the compiler if CRYPTO_EXAMPLE is not set in
*  the projectk.mk file. */
#ifdef CRYPTO_EXAMPLE
/* The simple crypto example included with the reference design is intended
*  to be an example of how you *may* use cryptography in your design. You
*  are not limited nor required to use this interface in your design. It is
*  recommended for newer teams to start by only using the simple crypto
*  library until they have a working design. */
#include "simple_crypto.h"
#endif  //CRYPTO_EXAMPLE

/**********************************************************
 ******************* PRIMITIVE TYPES **********************
 **********************************************************/

#define timestamp_t uint64_t
#define channel_id_t uint32_t
#define decoder_id_t uint32_t
#define pkt_len_t uint16_t
#define data_len_t uint32_t // just making it size of unsigned int so that packing the packet is easier > python has limited options

/**********************************************************
 *********************** CONSTANTS ************************
 **********************************************************/

#define MAX_CHANNEL_COUNT 8
#define EMERGENCY_CHANNEL 0
#define FRAME_SIZE 64
#define DEFAULT_CHANNEL_TIMESTAMP 0xFFFFFFFFFFFFFFFF
// This is a canary value so we can confirm whether this decoder has booted before
#define FLASH_FIRST_BOOT 0xDEADBEEF

/**********************************************************
 ********************* STATE MACROS ***********************
 **********************************************************/

// Calculate the flash address where we will store channel info as the 2nd to last page available
#define FLASH_STATUS_ADDR ((MXC_FLASH_MEM_BASE + MXC_FLASH_MEM_SIZE) - (2 * MXC_FLASH_PAGE_SIZE))

/**********************************************************
 *********** COMMUNICATION PACKET DEFINITIONS *************
 **********************************************************/

#pragma pack(push, 1) // Tells the compiler not to pad the struct members
// for more information on what struct padding does, see:
// https://www.gnu.org/software/c-intro-and-ref/manual/html_node/Structure-Layout.html
typedef struct {
    channel_id_t channel;
    timestamp_t timestamp;
    data_len_t size;
    // Change: Increased size of data to 16 + 64 bytes after adding frame_iv
    uint8_t data[16 + FRAME_SIZE];
} frame_packet_t;

typedef struct {
    decoder_id_t decoder_id;
    timestamp_t start_timestamp;
    timestamp_t end_timestamp;
    channel_id_t channel;
} subscription_update_packet_t;

typedef struct {
    channel_id_t channel;
    timestamp_t start;
    timestamp_t end;
} channel_info_t;

typedef struct {
    uint32_t n_channels;
    channel_info_t channel_info[MAX_CHANNEL_COUNT];
} list_response_t;

#pragma pack(pop) // Tells the compiler to resume padding struct members

/**********************************************************
 ******************** TYPE DEFINITIONS ********************
 **********************************************************/

typedef struct {
    bool active;
    channel_id_t id;
    timestamp_t start_timestamp;
    timestamp_t end_timestamp;
} channel_status_t;

typedef struct {
    uint32_t first_boot; // if set to FLASH_FIRST_BOOT, device has booted before.
    channel_status_t subscribed_channels[MAX_CHANNEL_COUNT];
} flash_entry_t;

/**********************************************************
 ************************ GLOBALS *************************
 **********************************************************/

// This is used to track decoder subscriptions
flash_entry_t decoder_status;

// global array to track the last processed timestamp per channel
static timestamp_t last_timestamps[MAX_CHANNEL_COUNT] = {0};

/**********************************************************
 ******************* UTILITY FUNCTIONS ********************
 **********************************************************/

/** @brief Checks whether the decoder is subscribed to a given channel
 *
 *  @param channel The channel number to be checked.
 *  @return 1 if the the decoder is subscribed to the channel.  0 if not.
*/
int is_subscribed(channel_id_t channel, timestamp_t timestamp) {
    // Check if this is an emergency broadcast message
    if (channel == EMERGENCY_CHANNEL) {
        return 1;
    }
    
    // Check if the decoder has has a subscription - > might be off by one error -> make sure it is not checking for channel 9
    for (int i = 0; i < MAX_CHANNEL_COUNT; i++) {

        // retrieves the start and end date of subscribtions for each channel
        // i.e. channel 1 start 1 end 100 -> time starts in boot and counts up
        uint64_t start = decoder_status.subscribed_channels[i].start_timestamp;
        uint64_t end = decoder_status.subscribed_channels[i].end_timestamp;
        // Ensure the channel is active and within the valid timestamp range
        if (decoder_status.subscribed_channels[i].id == channel && 
            decoder_status.subscribed_channels[i].active &&
            timestamp >= start && timestamp <= end) {

            // **Monotonic timestamp enforcement (only in RAM)**
            if (timestamp <= last_timestamps[i]) {
                STATUS_LED_RED();
                //print_debuug("------ Timestamp not increasing. Rejecting frame. ------");
                return 0; // Reject frame due to non-monotonic timestamp
            }

            // Update last processed timestamp (stored in RAM only)
            last_timestamps[i] = timestamp;

            return 1;
        }
    }
    return 0;
}


/**********************************************************
 ********************* CORE FUNCTIONS *********************
 **********************************************************/

/** @brief Lists out the actively subscribed channels over UART.
 *
 *  @return 0 if successful.
*/
int list_channels() {
    list_response_t resp;
    pkt_len_t len;

    resp.n_channels = 0;

    for (uint32_t i = 0; i < MAX_CHANNEL_COUNT; i++) {
        if (decoder_status.subscribed_channels[i].active) {
            resp.channel_info[resp.n_channels].channel =  decoder_status.subscribed_channels[i].id;
            resp.channel_info[resp.n_channels].start = decoder_status.subscribed_channels[i].start_timestamp;
            resp.channel_info[resp.n_channels].end = decoder_status.subscribed_channels[i].end_timestamp;
            resp.n_channels++;
        }
    }

    len = sizeof(resp.n_channels) + (sizeof(channel_info_t) * resp.n_channels);

    // Success message
    write_packet(LIST_MSG, &resp, len);
    return 0;
}


/** @brief Updates the channel subscription for a subset of channels.
 *
 *  @param pkt_len The length of the incoming packet
 *  @param update A pointer to an array of channel_update structs,
 *      which contains the channel number, start, and end timestamps
 *      for each channel being updated.
 *
 *  @note Take care to note that this system is little endian.
 *
 *  @return 0 upon success.  -1 if error.
*/
int update_subscription(pkt_len_t pkt_len, uint8_t *update) {
    //uint8_t decrypted_update[pkt_len];
    uint8_t decrypted_update[sizeof(subscription_update_packet_t)];  
    char debug_buf[100];

    // Debug: Received packet length
    // sprintf(debug_buf, "Received Packet Length: %d (Should be multiple of 16)", pkt_len);
    // print_debug(debug_buf);


    // Change: Changed to decrypt_cbc
    // Decrypting the incoming packet
    int check  = decrypt_cbc(update, pkt_len, (uint8_t*)secret_key, decrypted_update);
    if(check == 0){
        print_debug("Decryption Success! -> update_subscriptions()");
    }else if(check == -1){
        print_error("Decrypt failed size mismatch!");
    } 
    else{
        print_error("Decryption Failed! Invalid subscription update.");
        return -1;
    }

    // Triming off the padding from the frame data
    uint8_t trimmed_message[sizeof(subscription_update_packet_t)];
    memcpy(trimmed_message, decrypted_update, sizeof(subscription_update_packet_t));
    subscription_update_packet_t *safe_update = (subscription_update_packet_t *)decrypted_update;

    // sprintf(debug_buf, "channel ->  %i timestamp -> %llu", safe_update->channel, safe_update->start_timestamp);
    // print_debuug(debug_buf);
    
    // Debug: Check struct field values
    // sprintf(debug_buf, "Decoded Subscription - Device ID: %u, Start: %llu, End: %llu, Channel: %u", safe_update->decoder_id, safe_update->start_timestamp, safe_update->end_timestamp, safe_update->channel);
    // print_debug(debug_buf);


    // Debug: Check if the received structure size matches expected size
    // sprintf(debug_buf, "Struct Size Check - Expected: %lu, Received: %d", sizeof(subscription_update_packet_t), pkt_len);
    // print_debug(debug_buf);

    int i;

    // Check to not allowing re-subscription to emergency channel
    if (safe_update->channel == EMERGENCY_CHANNEL) {
        STATUS_LED_RED();
        print_error("Failed to update subscription - cannot subscribe to emergency channel\n");
        return -1;
    }

    // Find the first empty slot in the subscription array
    for (i = 0; i < MAX_CHANNEL_COUNT; i++) {
        if (decoder_status.subscribed_channels[i].id == safe_update->channel || !decoder_status.subscribed_channels[i].active) {
            decoder_status.subscribed_channels[i].active = true;
            decoder_status.subscribed_channels[i].id = safe_update->channel;
            decoder_status.subscribed_channels[i].start_timestamp = safe_update->start_timestamp;
            decoder_status.subscribed_channels[i].end_timestamp = safe_update->end_timestamp;
            break;
        }
    }

    // If we do not have any room for more subscriptions
    if (i == MAX_CHANNEL_COUNT) {
        STATUS_LED_RED();
        print_error("Failed to update subscription - max subscriptions installed\n");
        return -1;
    }

    flash_simple_erase_page(FLASH_STATUS_ADDR);
    flash_simple_write(FLASH_STATUS_ADDR, &decoder_status, sizeof(flash_entry_t));
    // Success message with an empty body
    write_packet(SUBSCRIBE_MSG, NULL, 0);
    return 0;
}


/**
 * @brief Processes a packet containing frame data.
 *
 * @param pkt_len Length of the incoming packet.
 * @param new_frame A pointer to the incoming packet.
 *
 * @return 0 if successful, -1 if data is from unsubscribed channel.
 */
// Change: Changed to Changed most of the function to accodmodate the new decryption
int decode(pkt_len_t pkt_len, uint8_t *new_frame) {
    char output_buf[128] = {0};
    char debug_buf[128] = {0};
    
    // check that the packet_len is not greater than the maximum packet size
    if(pkt_len > MAX_PACKET_SIZE){
        print_error("PACKET LENGTH EXCEEDS MAX PACKET SIZE");
        return -1;
    }

    // Debug: Received packet length
    sprintf(debug_buf, "Received Packet Length: %d bytes", pkt_len);
    print_debug(debug_buf);

    // Debug: Read encryption key from header file
    print_debug("DEBUG: READ ENCRYPTION KEY FROM HEADER FILE");
    print_hex_debug(secret_key, 16);


    /******************* Starting Outer Layer Decryption *******************/
    // Extracting the IV from the packet
    uint8_t first_layer_iv[16];
    memcpy(first_layer_iv, new_frame, 16);

    // Decrypt the first layer of the packet
    uint8_t first_decrypt[pkt_len - 16];
    int dec_ret = decrypt_cbc(new_frame + 16, pkt_len - 16, (uint8_t*)secret_key, first_decrypt);

    // Sanity Check: Check if there was error with packet length
    if(dec_ret == -1) print_debug("__________PACKET LENGTH ERROR__________");

    // Sanity Check: Check if the decryption of the first layer was successful
    if (dec_ret != 0) {
        print_debug("--------------- Failed to decrypt first frame layer ---------------------------");
        return -1; 
    }
    /******************* End of Outer Layer Decryption *******************/


    /******************* Start of Valid Decryption Checks and Frame Decryption *******************/
    // Extracting the channels, timestamps, size, and frame IV
    uint8_t frame_iv[16];
    memcpy(frame_iv, first_decrypt + 16, 16);  // Extract the frame IV

    // Cast the raw data as a frame_packet type in order to easily read the data. (the member data also has the frame IV and the padding)
    frame_packet_t *decrypted_packet = (frame_packet_t *)first_decrypt;

    // Calculate the size of the Padded frame data (size of the frame + padding)
    int padded_data_size = 0;
    if(((int)decrypted_packet->size % 16) != 0){
        padded_data_size = (decrypted_packet->size + (16 - ((int)decrypted_packet->size % 16)));
        sprintf(debug_buf, "********* Calculated size of padded data = %d ***********", padded_data_size);
        print_debug(debug_buf);
    }
    else{
        padded_data_size = decrypted_packet->size;
    }

    // Functional Requirement: Check subscription validity
    if (is_subscribed(decrypted_packet->channel, decrypted_packet->timestamp)) {

        uint8_t decrypted_message[padded_data_size];
        memcpy(decrypted_message, decrypted_packet->data + 16, padded_data_size);

        // Decrypt the frame data
        if (decrypt_cbc(decrypted_packet->data, padded_data_size + 16, (uint8_t*)secret_key, decrypted_message) != 0) {
            print_debug("Failed to decrypt message");
            return -1;
        }

        // Trim off the padding from the frame data
        uint8_t trimmed_message[decrypted_packet->size];
        memcpy(trimmed_message, decrypted_message, decrypted_packet->size);

        // Send the decrypted frame data to the host
        write_packet(DECODE_MSG, trimmed_message, (uint16_t)decrypted_packet->size);
        return 0;
    }
    else {
        STATUS_LED_RED();
        sprintf(output_buf, "Receiving unsubscribed channel data. Channel: %u", decrypted_packet->channel);
        // print_debug(output_buf);
        return -1;
    }

    /******************* End of Valid Decryption Checks and Frame Decryption *******************/
}



// TODO: remove all debug ports and all other security concerns!
/** @brief Initializes peripherals for system boot.
*/
void init() {
    int ret;

    // Initialize the flash peripheral to enable access to persistent memory
    flash_simple_init();


    // Read starting flash values into our flash status struct
    flash_simple_read(FLASH_STATUS_ADDR, &decoder_status, sizeof(flash_entry_t));
    


    if (decoder_status.first_boot != FLASH_FIRST_BOOT) {
        /* If this is the first boot of this decoder, mark all channels as unsubscribed.
        *  This data will be persistent across reboots of the decoder. Whenever the decoder
        *  processes a subscription update, this data will be updated.
        */
        //print_debuug("First boot.  Setting flash...\n");

        decoder_status.first_boot = FLASH_FIRST_BOOT;

        channel_status_t subscription[MAX_CHANNEL_COUNT];

        for (int i = 0; i < MAX_CHANNEL_COUNT; i++){
            subscription[i].start_timestamp = DEFAULT_CHANNEL_TIMESTAMP;
            subscription[i].end_timestamp = DEFAULT_CHANNEL_TIMESTAMP;
            subscription[i].active = false;
        }

        // Write the starting channel subscriptions into flash.
        memcpy(decoder_status.subscribed_channels, subscription, MAX_CHANNEL_COUNT*sizeof(channel_status_t));

        flash_simple_erase_page(FLASH_STATUS_ADDR);
        flash_simple_write(FLASH_STATUS_ADDR, &decoder_status, sizeof(flash_entry_t));
    }

    // Initialize the uart peripheral to enable serial I/O
    ret = uart_init();
    if (ret < 0) {
        STATUS_LED_ERROR();
        // if uart fails to initialize, do not continue to execute
        while (1);
    }
}

/**********************************************************
 *********************** MAIN LOOP ************************
 **********************************************************/

 #include <stdio.h>
 #include <stdint.h>
 
 int main(void) {
     char output_buf[128] = {0}; // Buffer for formatted debug messages
     uint8_t uart_buf[100]; // check overflows here and elsewhere!!!!!!
     msg_type_t cmd;
     int result;
     uint16_t pkt_len;
 
     // Initialize the device
     init();
 
     // Debug: Boot message
     //print_debuug("Decoder Booted!");
 
     // Print size of frame_packet_t
     sprintf(output_buf, "Size of frame_packet_t: %d bytes", (int)sizeof(frame_packet_t));
     //print_debuug(output_buf);
 
     // Print size of pkt_len
     sprintf(output_buf, "Size of pkt_len: %d bytes", (int)sizeof(pkt_len));
     //print_debuug(output_buf);
 
     // Process commands forever
     while (1) {
         //print_debuug("Ready");
 
         //STATUS_LED_GREEN();
         STATUS_LED_WHITE();
        
         result = read_packet(&cmd, uart_buf, &pkt_len);
        
         // Debug: Print command received
         sprintf(output_buf, "Received Command: %d", cmd);
         //print_debuug(output_buf);
 
         // Debug: Print packet length
         sprintf(output_buf, "Packet Length: %d bytes", pkt_len);
         //print_debuug(output_buf);
 
         if (result < 0) {
             STATUS_LED_ERROR();
             print_error("Failed to receive cmd from host");
             continue;
         }
 
         // Handle the requested command
         switch (cmd) {
         case LIST_MSG:
             STATUS_LED_CYAN();
             //print_debuug("Executing: LIST_MSG");
             list_channels();
             break;
 
         case DECODE_MSG:
             STATUS_LED_PURPLE();
             //print_debuug("Executing: DECODE_MSG");
             decode(pkt_len, uart_buf);
             break;
 
         case SUBSCRIBE_MSG:
             STATUS_LED_YELLOW();
             //print_debuug("Executing: SUBSCRIBE_MSG");
             update_subscription(pkt_len, uart_buf);
             break;
 
         default:
             STATUS_LED_ERROR();
             sprintf(output_buf, "Invalid Command: %c", cmd);
             print_error(output_buf);
             break;
         }
     }
 }
 